# Generated by Django 4.0.4 on 2023-03-29 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogpost', to=settings.AUTH_USER_MODEL),
        ),
    ]
