# Generated by Django 4.0.4 on 2023-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calcresponse_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcresponse',
            name='num1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calcresponse',
            name='num2',
            field=models.TextField(),
        ),
    ]
