# Generated by Django 4.0.4 on 2023-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_calcresponse_num1_alter_calcresponse_num2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcresponse',
            name='calc_answer',
            field=models.TextField(),
        ),
    ]
