# Generated by Django 4.0.4 on 2023-02-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_calcresponse_calc_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcresponse',
            name='calc_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calcresponse',
            name='num1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calcresponse',
            name='num2',
            field=models.IntegerField(),
        ),
    ]
