# Generated by Django 4.0.4 on 2022-12-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_rename_rate_cartproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='price',
            new_name='rate',
        ),
    ]
