# Generated by Django 4.0.4 on 2023-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_rename_rate_cartproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
