# Generated by Django 4.0.4 on 2023-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
    ]
