# Generated by Django 4.0.4 on 2023-01-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_rename_adress_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='price',
            new_name='rate',
        ),
    ]
