# Generated by Django 4.0.4 on 2023-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0009_order_order_status_order_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('PayU', 'PayU')], default='Cash On Delivery', max_length=20),
        ),
    ]
