# Generated by Django 4.0.4 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_product_view_count_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=50),
        ),
    ]
