# Generated by Django 4.0.4 on 2023-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
