# Generated by Django 3.2.5 on 2022-06-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='compartment',
            field=models.CharField(choices=[('comp1', 'Comp1'), ('comp2', 'Comp2'), ('comp3', 'Comp3'), ('comp4', 'Comp4')], default='comp1', max_length=25),
        ),
    ]
