# Generated by Django 3.2.5 on 2022-06-29 16:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticketApp', '0003_ticket_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('compartment', models.CharField(choices=[('comp1', 'Comp1'), ('comp2', 'Comp2'), ('comp3', 'Comp3'), ('comp4', 'Comp4')], default='comp1', max_length=25)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
