# Generated by Django 3.2.5 on 2022-07-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_remove_ticket_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='compartment',
            field=models.CharField(choices=[('comp1', 'Comp1'), ('comp2', 'Comp2'), ('comp3', 'Comp3'), ('comp4', 'Comp4')], default=None, max_length=25),
        ),
    ]
