# Generated by Django 4.0.4 on 2022-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0006_auto_20220704_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='compartment',
            field=models.CharField(choices=[('comp1', 'Comp1'), ('comp2', 'Comp2'), ('comp3', 'Comp3'), ('comp4', 'Comp4')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
